
services:
  django:
    build: ./django-app
    env_file:
      - ./django-app/secrets.env
    ports:
      - "8000:8000"
    volumes:
      - ./django-app:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - REDIS_URL=redis://redis:6379/0
    networks:
      - app-network
    depends_on:
      - redis

  react:
    build: ./react-app
    ports:
      - "5000:3000"
    volumes:
      - ./react-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0 
      - REACT_APP_API_URL=http://django:8000
      - PORT=3000
    networks:
      - app-network
    depends_on:
      - django

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

