# Generated by Django 4.2.7 on 2025-04-29 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6)])),
                ('level', models.PositiveIntegerField()),
                ('xp', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('streak', models.PositiveIntegerField()),
                ('english_answered', models.PositiveIntegerField()),
                ('maths_answered', models.PositiveIntegerField()),
                ('science_answered', models.PositiveIntegerField()),
                ('english_correct', models.PositiveIntegerField()),
                ('maths_correct', models.PositiveIntegerField()),
                ('science_correct', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField()),
                ('avatar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReEngage.avatar')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReEngage.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='avatars',
            field=models.ManyToManyField(through='ReEngage.StudentAvatar', to='ReEngage.avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='managed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReEngage.admin'),
        ),
        migrations.AddConstraint(
            model_name='studentavatar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_equipped', True)), fields=('student_id',), name='single_avatar_equipped'),
        ),
        migrations.AlterUniqueTogether(
            name='studentavatar',
            unique_together={('student_id', 'avatar_id')},
        ),
    ]
