# Generated by Django 4.2.7 on 2025-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReEngage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='firstname',
            field=models.CharField(default='def', max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='surname',
            field=models.CharField(default='def', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='def', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='def', max_length=20),
        ),
    ]
