# Generated by Django 4.2.7 on 2025-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReEngage', '0002_admin_firstname_admin_is_admin_admin_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='english_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_answered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
