# Generated by Django 4.2.7 on 2025-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReEngage', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_streak_check',
            field=models.DateField(blank=True, null=True),
        ),
    ]
